CREATE TABLE products(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCAHR(20) NOT NULL,
    price INT UNSIGNED NOT NULL,
    stock INT UNSIGNED DEFAULT 0,
    detail VARCAHR(1000)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
